{% set version = "0.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-paws.compute
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/paws.compute_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/paws.compute/paws.compute_{{ version }}.tar.gz
  sha256: be261081e2c54fadd8e0a00e516edb87a8feccf52d0eb223bc0554d5a25e186e

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-paws.common >=0.8.0
  run:
    - r-base
    - r-paws.common >=0.8.0

test:
  commands:
    - $R -e "library('paws.compute')"           # [not win]
    - "\"%R%\" -e \"library('paws.compute')\""  # [win]

about:
  home: https://github.com/paws-r/paws
  license: Apache-2.0
  summary: Interface to 'Amazon Web Services' compute services, including 'Elastic Compute Cloud' ('EC2'), 'Lambda' functions-as-a-service, containers, batch processing, and more <https://aws.amazon.com/>.
  license_family: APACHE
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - conda-forge/r
    - achimgaedke

# Package: paws.compute
# Title: 'Amazon Web Services' Compute Services
# Version: 0.1.12
# Authors@R: c(person(given = "David", family = "Kretch", role = c("aut", "cre"), email = "david.kretch@gmail.com"), person(given = "Adam", family = "Banker", role = "aut", email = "adam.banker39@gmail.com"), person(given = "Amazon.com, Inc.", role = "cph"))
# Description: Interface to 'Amazon Web Services' compute services, including 'Elastic Compute Cloud' ('EC2'), 'Lambda' functions-as-a-service, containers, batch processing, and more <https://aws.amazon.com/>.
# License: Apache License (>= 2.0)
# URL: https://github.com/paws-r/paws
# BugReports: https://github.com/paws-r/paws/issues
# Imports: paws.common (>= 0.3.0)
# Suggests: testthat
# Encoding: UTF-8
# RoxygenNote: 7.1.1
# Collate: 'batch_service.R' 'batch_interfaces.R' 'batch_operations.R' 'ec2_service.R' 'ec2_interfaces.R' 'ec2_operations.R' 'ec2instanceconnect_service.R' 'ec2instanceconnect_interfaces.R' 'ec2instanceconnect_operations.R' 'ecr_service.R' 'ecr_interfaces.R' 'ecr_operations.R' 'ecs_service.R' 'ecs_interfaces.R' 'ecs_operations.R' 'eks_service.R' 'eks_interfaces.R' 'eks_operations.R' 'elasticbeanstalk_service.R' 'elasticbeanstalk_interfaces.R' 'elasticbeanstalk_operations.R' 'lambda_service.R' 'lambda_interfaces.R' 'lambda_operations.R' 'lightsail_service.R' 'lightsail_interfaces.R' 'lightsail_operations.R' 'serverlessapplicationrepository_service.R' 'serverlessapplicationrepository_interfaces.R' 'serverlessapplicationrepository_operations.R'
# NeedsCompilation: no
# Packaged: 2021-08-22 21:45:08 UTC; david.kretch
# Author: David Kretch [aut, cre], Adam Banker [aut], Amazon.com, Inc. [cph]
# Maintainer: David Kretch <david.kretch@gmail.com>
# Repository: CRAN
# Date/Publication: 2021-08-23 07:11:03 UTC
